### PR TITLE
kdeconnect-kde: use stable versions

### LINKED ISSUE #2: kdeconnect-kde: use stable versions instead of ones from CI
Hi, thanks a lot for maintaining this package! Here is a minor issue: I often got download failures during upgrades. For example, the current versions gives:

```
You have kdeconnect-kde v22.04.0.952 installed. Version 22.04.1.973 is available based on your source(s).
Progress: Downloading kdeconnect-kde 22.04.1.973... 100%

kdeconnect-kde v22.04.1.973 [Approved]
kdeconnect-kde package files upgrade completed. Performing other installation steps.
The package kdeconnect-kde wants to run 'ChocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Downloading kdeconnect-kde
  from 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/973/artifact/kdeconnect-kde-22.04.1-973-windows-msvc2019_64-cl.exe'
Progress: 46% - Saving 29.41 MB of 63.43 MB
Download of kdeconnect-kde-22.04.1-973-windows-msvc2019_64-cl.exe (63.43 MB) completed.
ERROR: Chocolatey expected a file at 'C:\Users\yen\AppData\Local\Temp\chocolatey\kdeconnect-kde\22.04.1.973\kdeconnect-kde-22.04.1-973-windows-msvc2019_64-cl.exe' to be of length '66510288' but the length was '30843341'.
The upgrade of kdeconnect-kde was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\kdeconnect-kde\tools\ChocolateyInstall.ps1'.
 See log for details.
 Unsuccessful operation for kdeconnect-kde.
  Rollback to previous version (package files only)?([Y]es/[N]o): y
```

I noticed that https://binary-factory.kde.org/ runs Jenkins CI. I guess those files are auto-generated for testing, not for daily-use. Could you consider use "Offline Installers" mentioned https://kdeconnect.kde.org/download.html instead?

### PR DESCRIPTION
**Pull request by yan12125**
Also cleanups unused variables

Closes https://github.com/AndreAugustoAAQ/chocolatey-packages/issues/2

### CODE REVIEW

**Comment by yan12125** [comment]
The installer URL may not be in the first `<release>` tag. For example, from https://invent.kde.org/network/kdeconnect-kde/-/blob/ccb4a62f9c350a8c8fcfcc46361500b7033e4534/data/org.kde.kdeconnect.metainfo.xml,

```XML
  <releases>
    <release version="23.04.0" date="2023-04-20"/>
    <release version="22.12.3" date="2023-03-02">
      <artifacts>
        <artifact type="binary" platform="x86_64-windows-msvc">
          <location>https://download.kde.org/stable/release-service/22.12.3/windows/kdeconnect-kde-22.12.3-1284-windows-cl-msvc2019-x86_64.exe</location>
          <checksum type="sha256">0392238972a5f0425164858ce5ad31959847c94b41418f5d95a77733caf60949</checksum>
          <size type="download">68705704</size>
        </artifact>
      </artifacts>
    </release>
    <release version="22.12.2" date="2023-02-02"/>
    <release version="22.12.1" date="2023-01-05"/>
  </releases>
```

As a result, I switched to a loop to find the proper `<release>` tag.

**Comment by yan12125** [comment]
Patch v3: correct handle cases where there are 2 or more releases with installer URLs. For example, from https://invent.kde.org/network/kdeconnect-kde/-/blob/8fed0728dadfc9badf9482b3e045dfdf5640e830/data/org.kde.kdeconnect.metainfo.xml,
```XML
  <releases>
    <release version="23.04.0" date="2023-04-20">
      <artifacts>
        <artifact type="binary" platform="x86_64-windows-msvc">
          <location>https://download.kde.org/stable/release-service/23.04.0/windows/kdeconnect-kde-23.04.0-1322-windows-cl-msvc2019-x86_64.exe</location>
          <checksum type="sha256">b32a83ac7f89f284c2330b5dd01f430294d1adb201ab5c0f11aae19f29866eae</checksum>
          <size type="download">68822496</size>
        </artifact>
      </artifacts>
    </release>
    <release version="22.12.3" date="2023-03-02">
      <artifacts>
        <artifact type="binary" platform="x86_64-windows-msvc">
          <location>https://download.kde.org/stable/release-service/22.12.3/windows/kdeconnect-kde-22.12.3-1284-windows-cl-msvc2019-x86_64.exe</location>
          <checksum type="sha256">0392238972a5f0425164858ce5ad31959847c94b41418f5d95a77733caf60949</checksum>
          <size type="download">68705704</size>
        </artifact>
      </artifacts>
    </release>
    <release version="22.12.2" date="2023-02-02"/>
    <release version="22.12.1" date="2023-01-05"/>
  </releases>
```
To correctly handle this, I switched to `foreach` instead of `Foreach-Object`, as `break` does not work with the latter [1], and thus older installer URL overrides the newer one.

[1] https://stackoverflow.com/questions/10277994/how-to-exit-from-foreach-object-in-powershell

**Comment by opusforlife2** [comment]
Awesome! Thanks for this!

**Comment by opusforlife2** [comment]
The script doesn't seem to have worked for 23.08?

**Comment by yan12125** [comment]
> The script doesn't seem to have worked for 23.08?

This script relies on upstream XML data, and the latter is not updated for 23.08 yet. I proposed the fix at https://invent.kde.org/network/kdeconnect-kde/-/merge_requests/628

**Pull request merged**
